name: Reload on PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger reload webhook
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{ secrets.RELOAD_URL }}
        method: 'GET'
        customHeaders: '{"Authorisation": "Bearer ${{ secrets.DEPLOY_TOKEN }}"}'
